<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV6EWzyg\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV6EWzyg/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerV6EWzyg.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerV6EWzyg\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerV6EWzyg\App_KernelProdContainer([
    'container.build_hash' => 'V6EWzyg',
    'container.build_id' => '7da05ee1',
    'container.build_time' => 1701694325,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV6EWzyg');
