<?php

namespace ContainerV6EWzyg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHorarioRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\HorarioRepository' shared autowired service.
     *
     * @return \App\Repository\HorarioRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\HorarioRepository'] = new \App\Repository\HorarioRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
