<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAOxmsZN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAOxmsZN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAOxmsZN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAOxmsZN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAOxmsZN\App_KernelDevDebugContainer([
    'container.build_hash' => 'AOxmsZN',
    'container.build_id' => 'bb0390f5',
    'container.build_time' => 1701692422,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAOxmsZN');
