<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '79af482305348517e69d76572d971657',
  'DATABASE_URL' => 'mysql://cdr95689_productora:FUdngqQ.GIT+@127.0.0.1:3306/cdr95689_productora?serverVersion=8.0.32&charset=utf8mb4',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'MAILER_DSN' => 'smtp://_mainaccount@dreamproductora.cl:chULIIFnIItrQjWxdtRE@mail.dreamproductora.cl:465',
);
