<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PresupuestoServicio extends \App\Entity\PresupuestoServicio implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'cantidad' => [parent::class, 'cantidad', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'id_presupuesto' => [parent::class, 'id_presupuesto', null],
        "\0".parent::class."\0".'servicio' => [parent::class, 'servicio', null],
        "\0".parent::class."\0".'subtotal' => [parent::class, 'subtotal', null],
        "\0".parent::class."\0".'valor' => [parent::class, 'valor', null],
        'cantidad' => [parent::class, 'cantidad', null],
        'id' => [parent::class, 'id', null],
        'id_presupuesto' => [parent::class, 'id_presupuesto', null],
        'servicio' => [parent::class, 'servicio', null],
        'subtotal' => [parent::class, 'subtotal', null],
        'valor' => [parent::class, 'valor', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
