<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Presupuesto extends \App\Entity\Presupuesto implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'cliente' => [parent::class, 'cliente', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'estado' => [parent::class, 'estado', null],
        "\0".parent::class."\0".'fecha' => [parent::class, 'fecha', null],
        "\0".parent::class."\0".'fono' => [parent::class, 'fono', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'n_presupuesto' => [parent::class, 'n_presupuesto', null],
        "\0".parent::class."\0".'total' => [parent::class, 'total', null],
        'cliente' => [parent::class, 'cliente', null],
        'email' => [parent::class, 'email', null],
        'estado' => [parent::class, 'estado', null],
        'fecha' => [parent::class, 'fecha', null],
        'fono' => [parent::class, 'fono', null],
        'id' => [parent::class, 'id', null],
        'n_presupuesto' => [parent::class, 'n_presupuesto', null],
        'total' => [parent::class, 'total', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
