<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cliente extends \App\Entity\Cliente implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'correo' => [parent::class, 'correo', null],
        "\0".parent::class."\0".'direccion' => [parent::class, 'direccion', null],
        "\0".parent::class."\0".'estado' => [parent::class, 'estado', null],
        "\0".parent::class."\0".'fecha' => [parent::class, 'fecha', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'iva' => [parent::class, 'iva', null],
        "\0".parent::class."\0".'nombre' => [parent::class, 'nombre', null],
        "\0".parent::class."\0".'telefono' => [parent::class, 'telefono', null],
        "\0".parent::class."\0".'valor' => [parent::class, 'valor', null],
        'correo' => [parent::class, 'correo', null],
        'direccion' => [parent::class, 'direccion', null],
        'estado' => [parent::class, 'estado', null],
        'fecha' => [parent::class, 'fecha', null],
        'id' => [parent::class, 'id', null],
        'iva' => [parent::class, 'iva', null],
        'nombre' => [parent::class, 'nombre', null],
        'telefono' => [parent::class, 'telefono', null],
        'valor' => [parent::class, 'valor', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
