<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Reserva extends \App\Entity\Reserva implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'id_cliente' => [parent::class, 'id_cliente', null],
        "\0".parent::class."\0".'id_horario' => [parent::class, 'id_horario', null],
        "\0".parent::class."\0".'ids_servicio' => [parent::class, 'ids_servicio', null],
        "\0".parent::class."\0".'reserva' => [parent::class, 'reserva', null],
        'id' => [parent::class, 'id', null],
        'id_cliente' => [parent::class, 'id_cliente', null],
        'id_horario' => [parent::class, 'id_horario', null],
        'ids_servicio' => [parent::class, 'ids_servicio', null],
        'reserva' => [parent::class, 'reserva', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
